### ISSUE TITLE
DotNetCoreBuild VS2017 csproj not supported

### ISSUE THREAD

**Issue by mvput** [cake-contrib/Cake.Incubator#10]
Trying to build a .NETCore Console Application created with VS2017 RC using cake. Following line is used for executing the build.

DotNetCoreBuild("./src/ConsoleApplication1/ConsoleApplication1.csproj", settings);

When running the script the task fails with error:

An error occurred when executing task 'Build'. Error: Cake.Core.CakeException: Failed to parse project properties at Cake.Incubator.CustomProjectParser.ParseCsProjFile(FilePath projectPath, String config) at Cake.Incubator.ProjectParserExtensions.ParseProject(ICakeContext context, FilePath project, String configuration) at Submission#0.CopyBuildOutput() at Submission#0.<.ctor>b__10() at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass5_0.<Does>b__0(ICakeContext context) at Cake.Core.ActionTask.Execute(ICakeContext context) at Cake.Core.DefaultExecutionStrategy.Execute(CakeTask task, ICakeContext context) at Cake.Core.CakeEngine.ExecuteTask(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) at Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy strategy, String target) at Cake.Scripting.BuildScriptHost.RunTarget(String target) at Submission#0.<get_Build>b__0(String target) at Submission#0.<Factory>(Session session) at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session session, Boolean isInteractive) at Roslyn.Scripting.Session.Execute(String code) at Cake.Scripting.Roslyn.Stable.DefaultRoslynScriptSession.Execute(Script script) at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary2 arguments) at Cake.Commands.BuildCommand.Execute(CakeOptions options) at Cake.CakeApplication.Run(CakeOptions options) at Cake.Program.Main()

Looks like Cake.Incubator doesn't support VS2017 new csproj files. The csproj files look minimalistic compared to previous csproj files.

`<Project Sdk="Microsoft.NET.Sdk"> <PropertyGroup> <OutputType>Exe</OutputType> <TargetFramework>netcoreapp1.0</TargetFramework> </PropertyGroup> </Project>`

Using the cli with the command: dotnet build src\ConsoleApplication1\ConsoleApplication1.csproj does work.

Other DotNetCore commands available in cake i didn't test but looks to me it works the same as DotNetCoreBuild for parsing projects.

**Comment by wwwlicious** [comment]
Indeed I haven't tested this with VS2017 but given how reduced the contents of the csproj files are it isn't that surprising. 

Depending on some of the changes made, it might be difficult to obtain the same level of information as a VS2015 csproj file but I'll take a look this week.

**Comment by gep13** [comment]
@wwwlicious this might actually best be served by another alias as well. What do you think?

**Comment by mvput** [comment]
@wwwlicious perhaps `TargetFramework `can provide enough information to distinct `netcoreapp `or `netstandard `from normal csproj files. This seems more than enough information to know I think for that kind of projects. Additional information such as Project SDK can also be handy.

**Comment by mvput** [comment]
The standard .NET Framework csproj files look mostly the same as VS2015 csproj files. Check https://gist.github.com/mvput/b838d8bf902580866f46a66acde710c0

**Comment by wwwlicious** [comment]
@mvput thanks.

If `TargetFramework` always for a single target and has a distinct value then yes, that would be ideal to switch project parsers.

@gep13 yes I would probably create a new alias to specifically parse a dotnetcore project but would also edit the existing alias to detect the type and use the appropriate parser .. **if** it is appropriate to use the same return value `CustomProjectParserResult`. Usually prefer to make my impl somewhat agnostic.

**Comment by mrahhal** [comment]
Hi, any update on this now that the 1.0 tooling has RTM'd? I'm migrating a long list of some projects to the new tooling for which I controlled the build process using cake.

**Comment by wwwlicious** [comment]
Initial support for basic parsing has been added to allow detection of output type (dll or exe) and output path (bin/{config}) so that parserResult.GetOutputAssembly() will work.

Files, References are not yet included as Guid's and rootnamespaces as far as I know are no longer relevant

You should just be able to use the existing parser and it will detect the right parser for the project file.

**Comment by wwwlicious** [comment]
Closing for now with basic support now added. 
Please open separate issue for additional properties as required (Files, References, ProjectReferences etc)
