### ISSUE TITLE
Dump Logging Extension not working

### ISSUE THREAD

**Issue by toddstewart** [cake-contrib/Cake.Incubator#100]
I upgraded to Cake.Incubator to version 4.0.1 and the place where I was using the Dump() logging extension starting failing.  The only way to get it to work was to add "using Cake.Incubator.LoggingExtensions;" to the cake file.  The cake file is from a nuget package similar in setup to Cake.Recipe.

**Comment by wwwlicious** [comment]
Thanks for reporting. As far as I know, the namespaces should be automatically imported by cake.

Any input on this @gep13 ?

**Comment by phantomtypist** [comment]
Workaround works.  FWIW I'm pinned to between 0.26.1 and 0.28.0 of Cake due to another add-in not being updated.

**Comment by phantomtypist** [comment]
@wwwlicious I guess this is related to https://github.com/cake-contrib/Cake.Incubator/issues/96 and further https://github.com/cake-build/cake/issues/2487

**Comment by toddstewart** [comment]
The current method of adding [CakeNamespaceImport("Cake.Incubator.LoggingExtensions")] to the LoggingExtensions class will not work since the class does not contain a method or property that extends ICakeContext.  To get the namespace added I added the following to the csproj file.

  <ItemGroup>
    <AssemblyAttribute Include="Cake.Core.Annotations.CakeNamespaceImportAttribute">
      <_Parameter1>Cake.Incubator.LoggingExtensions</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

Doing this fixed the issue I was having trying to use Dump.

The csproj file will need to be updated with all of the namespaces of extensions that are not extending ICakeContext.

**Comment by wwwlicious** [comment]
@toddstewart awesome, thank you!
