### ISSUE TITLE
dotnet 5 not recognized as netcore

### ISSUE THREAD

**Issue by mryanmurphy** [cake-contrib/Cake.Incubator#116]
`net5.0` should be parsed as a netcore target framework instead of a netframework target framework. 

In all of the codepaths that include a conditional on `IsNetCore`, the wrong branch is taken for `net5.0` trying to treat it as net framework csproj file.

https://github.com/cake-contrib/Cake.Incubator/blob/ccccbc0ae68a3a8156769286eee1daab9a7989da/src/Cake.Incubator/Project/ProjectParserExtensions.cs#L34-L36

**Comment by nils-a** [comment]
One point here is that `net5.0` is matched as `IsNetFramework`, the other that there is no `IsNet` (or `IsNet5Plus` or something like that) is missing entirely.

Additionally, looking at the RegEx, the TFMs for "Windows Store" (`netcore`, `netcore45`, `netcore451`) would be wrongly recognized as `IsNetCore`

(And, on a sidenote, the RegEx seem to awfully complex for the task required...)
