### ISSUE TITLE
Replace Gitter with GitHub Discussions

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.Incubator#117]
The Discussion platform for Cake-Contrib has been moved from Gitter to GitHub Discussion (see cake-build/website#1470). 
Please check this repo for references to Gitte and replace them accordingly.

Search suggests that references could be in

 - docs/input/blog/new-release-1.1.1.md
 - docs/input/blog/new-release-1.1.0.md
 - docs/input/blog/new-release-1.3.0.md
 - docs/input/blog/new-release-1.2.0.md
 - docs/input/blog/new-release-1.4.0.md

**Comment by gep13** [comment]
@nils-a this has been completed.  Thanks for reporting this!
