### ISSUE TITLE
Adding Imports to CustomProjectParserResult

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Incubator#12]
@wwwlicious Do you know if there is enough of a "standard" in the way that Imports are handled in a project to allow the reporting on what targets have been included in any given project?

**Comment by wwwlicious** [comment]
I'm not sure what you mean exactly but given that I went spelunking into VS2017 csproj files for the first time tonight, I'm still at the 'figuring things out' stage, a lot of stuff is defaulted if not there so I'm learning to do more with less! 

You got an example file you could give me?

**Comment by gep13** [comment]
@wwwlicious this is not specifically for 2017 projects.  Take this csproj as an example:

https://github.com/cake-contrib/Cake.VsMetrics/blob/master/Source/Cake.VsMetrics.Tests/Cake.VsMetrics.Tests.csproj

I am trying to parse it in order to reliably figure out what Unit Testing Framework is being used.  Normally, I just look at the references, but you will see in this case, that the reference in question is locked behind a `Choose`

```
<Choose>
    <When Condition="('$(VisualStudioVersion)' == '10.0' or '$(VisualStudioVersion)' == '') and '$(TargetFrameworkVersion)' == 'v3.5'">
      <ItemGroup>
        <Reference Include="Microsoft.VisualStudio.QualityTools.UnitTestFramework, Version=10.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL" />
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <Reference Include="Microsoft.VisualStudio.QualityTools.UnitTestFramework">
          <Private>False</Private>
        </Reference>
      </ItemGroup>
    </Otherwise>
  </Choose>
```

which means the current parser can't find the reference.

If I look at the `Imports` at the bottom of the file, I can assert the framework being used:

```
<Import Project="$(VSToolsPath)\TeamTest\Microsoft.TestTools.targets" Condition="Exists('$(VSToolsPath)\TeamTest\Microsoft.TestTools.targets')" />
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
```

but these are not currently returned from the parser.

**Comment by wwwlicious** [comment]
Well it looks like getting the import elements project value would be easy, but checking the conditions are valid for the import to actually succeed relies on msbuild which is not really possible in the parser which is just looking at the xml

**Comment by wwwlicious** [comment]
@gep13  Do you have a specific use-case btw, kinda interesting idea?

**Comment by gep13** [comment]
@wwwlicious So, just to confirm we are on the same page...

Within Cake.Recipe, I want to be able to pass it a solution file, and for it to do all the rest.  This means iterating over the projects contained within the solution, and making an informed decision about what that project is, and what post-processing is required.  So for example, after compilation of the solution, if a project contains a reference to the xunit libraries, I know I need to run the xunit console runner on the output of that project.  Same for any other testing framework that is currently supported, i.e. NUnit and MSTest.  Then, the output of all these testing projects are collected together using OpenCover and the output is uploaded to coveralls.io.

The inspection of the NUnit and xunit projects turned out to be really simple, but the MSTest project is proving to be a little harder.  Hence the question... 😄 

So either, I/we need to make the reference parser know about the `choose` option, or I need to use the `Imports` or something else, in order to assert that a particular project is using MSTest.

**Comment by wwwlicious** [comment]
@gep13 Sure that makes sense, surprised that MS Test is the awkward child....oh wait! ;)

I see where you are coming from, a couple of questions:

1. Do you detect that MS Tests are actually in the project, as running it just based on a reference which may not be needed?
2. Is it enough to just grab the first `reference` element inside any choose group and ignore the version (strip off everything after a comma) as the parser only needs to know the reference exists by name or does it have to know the versions in order to select the right runner?

Using the imports is problematic as the paths are always prefixes by something that will only be evaluated when compiling I think.

**Comment by gep13** [comment]
>@wwwlicious said...
Do you detect that MS Tests are actually in the project, as running it just based on a reference which may not be needed?

At the minute, this is just a first pass implementation.  If the reference is there, run the associated test runner.  No other smarts there, yet.

>@wwwlicious said...
Is it enough to just grab the first reference element inside any choose group and ignore the version (strip off everything after a comma) as the parser only needs to know the reference exists by name or does it have to know the versions in order to select the right runner?

Yeah, at the minute, the reference is the only thing I am interested in, don't really mind about the version and other information.

**Comment by gep13** [comment]
Sounds like your Linq fu is better than mine 😄
