### ISSUE TITLE
Using `DotNetCoreTest` extensions

### ISSUE THREAD

**Issue by fleed** [cake-contrib/Cake.Incubator#25]
Where can I find the documentation for the `XUnit2Settings` class as mentioned [here](http://cakebuild.net/api/Cake.Incubator/DotNetCoreTestExtensions/D1A1B351)?

**Comment by stuartbfs** [comment]
It's in the main cake project, reference is here:

http://cakebuild.net/api/Cake.Common.Tools.XUnit/XUnit2Settings/

**Comment by fleed** [comment]
Thank you @stuartbfs
