### ISSUE TITLE
Add PackageReference's to ParseNetcoreProjectFile method

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Incubator#28]
@wwwlicious are there any plans to add this into the parsing on the 2017 Project File?

i.e. would like to be able to have this information:

![image](https://cloud.githubusercontent.com/assets/1271146/26028964/2a78a632-3822-11e7-9e58-8b0c06e09d5f.png)

During build execution.

**Comment by wwwlicious** [comment]
@gep13 Sure, should be doable, will have a look tomorrow

**Comment by gep13** [comment]
@wwwlicious thank you very much! 😄

**Comment by gep13** [comment]
Nice one! 😄
