### ISSUE TITLE
Add ProjectReference's to ParseNetcoreProjectFile method

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Incubator#29]
@wwwlicious are there any plans to add this into the parsing on the 2017 Project File?

i.e. would like to be able to have this information:

![image](https://cloud.githubusercontent.com/assets/1271146/26028988/70cfba08-3822-11e7-89db-a0df203e2e63.png)

During build execution.

**Comment by wwwlicious** [comment]
@gep13 Again, should be doable, will have a look tomorrow

**Comment by gep13** [comment]
@wwwlicious that would be amazing, thank you!

**Comment by gep13** [comment]
Nice one! 😄
