### ISSUE TITLE
Expand netcore project support

### ISSUE THREAD

**Issue by wwwlicious** [cake-contrib/Cake.Incubator#30]
Now that the netcore project format is RTM and somewhat more stable, expand the parser to include many of the netcore specific properties in project filles detailed [here](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json-to-csproj)

To avoid breaking backward compatability, properties common to net framework and netcore willl still be populated to the `CustomProjectParserResult` class but any netcore specific properties will be added to a new properrty `NetCore` of `NetCoreProject` type on that class along with two bools`IsNetFramework` and `IsNetCore` to make idenifying the project result type easier.

**Comment by gep13** [comment]
Nice one! 😄

**Comment by wwwlicious** [comment]
just getting the release out, following your notes scrupulously! lol
