### ISSUE TITLE
Support for Runtimes in .NET Core Projects

### ISSUE THREAD

**Issue by kitforbes** [cake-contrib/Cake.Incubator#43]
Support for `RuntimeIdentifier` and `RuntimeIdentifiers` would be very useful for dynamically executing `DotNetCorePublish`, which requires a runtime value.

An example of this in a `csproj` file:

```xml
<PropertyGroup>
  <TargetFramework>netcoreapp2.0</TargetFramework>
  <OutputType>Exe</OutputType>
  <RuntimeIdentifiers>win10-x64;centos.7-x64</RuntimeIdentifiers>
</PropertyGroup>
```

**Comment by wwwlicious** [comment]
Hi @kitforbes,

thanks for raising this issue. The project parser already supports returning the runtime identifier/s.
http://cakebuild.net/api/Cake.Incubator/NetCoreProject/E464508B

Is there something beyond this that you had in mind regarding support?

**Comment by kitforbes** [comment]
Ah, I see. Looks like I was just using it wrong. Sorry!

I was running `ParseProject(project.Path, configuration).Dump()` and that didn't show a lot of the elements I was expecting to see. What do I need to do to get access to the `NetCoreProject` object?

**Comment by wwwlicious** [comment]
Dump doesn't recursively print child objects so
`ParseProject(project.Path, configuration).NetCore.Dump()` should do the trick

**Comment by kitforbes** [comment]
Yep, that did it. Thanks for the help.

The Cake documentation is nice, but I find it really confusing to find what I'm after on there.

**Comment by wwwlicious** [comment]
Perhaps you could raise an issue on their repo for the website. They have always been great and happy to help.

/cc @gep13

**Comment by gep13** [comment]
@wwwlicious :+1:

I was just coming here to say the same thing.

@kitforbes if there is something specific that you think is missing, or could be done better, then we are all ears.

**Comment by kitforbes** [comment]
I'll try to compose my thoughts into something coherent.
