### ISSUE TITLE
ParseProject will throw exception when encountering absolute path

### ISSUE THREAD

**Issue by Insire** [cake-contrib/Cake.Incubator#44]
ParseProject will fail with an Error stating that 

> Cannot combine a directory path with an absolute file path.

when a project file contains a reference to an assembly with an absolute path

Example:

```
    <Reference Include="System">
      <HintPath>C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.dll</HintPath>
    </Reference>
```

[Stacktrace](https://gist.github.com/Insire/1e6d2acfaa477f3c2cb9b9e52e674a8e)

[Repro Project](https://github.com/cake-contrib/Cake.Incubator/files/1264739/ConsoleApp1.zip)

**Comment by wwwlicious** [comment]
@Insire Thanks for raising this, I'll look to get this fixed for the next release.

**Comment by Insire** [comment]
@wwwlicious Thanks, looking forward to it.

 I'm not sure if it fits inside the scope of this lib, but having absolute paths in a project file can be problematic. Would it be reasonable to print a warning to console, that there is an absolute path in a project file?

**Comment by wwwlicious** [comment]
@Insire good suggestion, I don't see what harm it would do to output a warning to the logs so I'll include this as part of the fix.
