### ISSUE TITLE
Upgrade to VS2017 and add .NET Core target

### ISSUE THREAD

**Issue by RLittlesII** [cake-contrib/Cake.Incubator#45]
So addin can be loaded from Cake CoreCLR runner

**Comment by gep13** [comment]
@wwwlicious you will likely need to bump the appveyor image in order to get things to work here, as per this:

https://github.com/cake-contrib/Cake.Coveralls/commit/1fd9fcd21cb68b3ae3d15679e1c48634dc76b121

**Comment by wwwlicious** [comment]
@gep13 thanks, will give it a try, having an issue with cake.receipe locally too though (object null reference) so prob more to do

**Comment by gep13** [comment]
Yip, was just typing a message about that too...

Change this:

https://github.com/cake-contrib/Cake.Incubator/blob/develop/setup.cake#L24

to `Build.RunDotNetCore();`

**Comment by gep13** [comment]
Just tested this locally, and builds for me locally.

**Comment by wwwlicious** [comment]
@gep13 build image is already set - https://github.com/cake-contrib/Cake.Incubator/blob/develop/.appveyor.yml#L33

Updated setup but getting dupfinder errors due to assemblyinfo.cs being generated per framework target!!

**Comment by gep13** [comment]
If you are not using the nuspec files (I noticed that you deleted them) you will need to add `shouldRunDotNetCorePack: true` to your call to `SetParameters`.

However, this might mean that the resulting nupkg's don't include the files that you would expect.

**Comment by gep13** [comment]
@wwwlicious said...
Updated setup but getting dupfinder errors due to assemblyinfo.cs being generated per framework target!!

ah, that is a `feature`!

Have a look here:

https://github.com/cake-contrib/Cake.Coveralls/blob/develop/setup.cake#L16

**Comment by gep13** [comment]
>@wwwlicious said...
build image is already set 

Ah, missed that.  I normally have it at the top of the file, so never looked anywhere else 😄

**Comment by wwwlicious** [comment]
@gep13 think I would be scratching my head with some of this stuff if not for your help so thanks! :)

Just updating things now.
I *think* the standard pack should be ok (works in VS anyway) as I don't include anything other than the dll (now one per framework target)

**Comment by wwwlicious** [comment]
@gep13 Getting some codeinspection issues now (mainly stuff that doesn't yet have unit test coverage so says it's unused. How best to exclude these?

**Comment by gep13** [comment]
I think I had to do it with the nuspec, as I wanted to include the documentation xml and pdb files.

Ah, the codeinspection is handled through the standard resharper configuration file.  If you don't want to go down that route, then you can set `shouldRunInspectCode: false` in the call to SetParameters.

**Comment by wwwlicious** [comment]
@gep13 good point, think I'll resurrect the nuspec file then. I take it that --include-symbols option to generate the nuget symbol package isn't supported right now?

**Comment by gep13** [comment]
@wwwlicious no, that one hasn't been included yet.  From a Cake.Recipe perspective, I have been using GitLink to update the pdb files, so a symbols package is not required, however, GitLink doesn't support .net core projects, and I haven't yet had the cycles to switch over to using SourceLink, which does support it.

That isn't to say that Cake.Recipe can't support that flag.

**Comment by wwwlicious** [comment]
@gep13 does `Build.RunDotNetCore()` not work with mixed projects? (lib is netstandard, test proj is net46)

**Comment by RLittlesII** [comment]
@wwwlicious yes it does.  You have to set the project targets in your .csproj file.

**Comment by gep13** [comment]
@wwwlicious it "should".

Are you seeing an issue?  It now builds fine locally for me.

**Comment by gep13** [comment]
@wwwlicious I have just cleared the AppVeyor Cache, and I am running the build again...

**Comment by gep13** [comment]
Ah, I think I see the problem....

**Comment by wwwlicious** [comment]
@gep13 me too I think, I haven't changes test project to vs2017, doing it now

**Comment by gep13** [comment]
Yip, I think these:

![image](https://user-images.githubusercontent.com/1271146/30324145-e45b1004-97b7-11e7-8f9a-b1bc0ae72aed.png)

Are throwing it for a spin.

**Comment by gep13** [comment]
As that path doesn't exist.
