### ISSUE TITLE
Update to Cake 0.22

### ISSUE THREAD

**Issue by tidusjar** [cake-contrib/Cake.Incubator#47]
Looks like this needs to build against cake 0.22 now! Just a heads up

**Comment by wwwlicious** [comment]
@tidusjar Thanks, the release 1.5.0 yesterday (just prior to the cake team releasing 0.22.0) bumps the dependency version to 0.21.1 but it isn't being picked up by nuget packaging so it's not obvious. Will see about correcting that.

I'll be updating to 0.22.0 for the next release (this also means dropping net45 support) 

For anyone who isn't ready to upgrade, as per the cake teams recommendation, please pin the cake.incubator version (in fact, any tool or addin versions) to avoid unwanted updates that may cause builds to break.

**Comment by devlead** [comment]
@tidusjar @wwwlicious I've proposed pr cake-contrib/Cake.Incubator#48 that doesn't drop 4.5 support by for now referencing older version of Cake for .NET 4.5 and newer for 4.6/1.6.
