### ISSUE TITLE
Make detecting TargetFramework for PackageReference more robust

### ISSUE THREAD

**Issue by evil-shrike** [cake-contrib/Cake.Incubator#51]
`ParseProject` reads PackageReference's from csprj and extracts TargetFramework from `Condition` attribute (it only can have a condition for `$(TargetFramework)` according to docs).
But that detection does just string comparison:

```
    public static class StringExtensions
    {
        private const string TargetframeworkCondition = "'$(TargetFramework)'==";

        internal static bool HasTargetFrameworkCondition(this string condition)
        {
            return !condition.IsNullOrEmpty() && condition.StartsWith(TargetframeworkCondition);
        }
}
```

If I have a space around "==" TargetFramework  won't be loaded. It's kinda unclear without looking into the code.
So at least Regexp should be used instead.

**Comment by wwwlicious** [comment]
Do you have a link to the docs you refer to, always helpful to work from?

I agree it could be more robust, it was a case of 'good enough' at the time. :)

**Comment by evil-shrike** [comment]
>Do you have a link to the docs you refer to, always helpful to work from?

https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#adding-a-packagereference-condition

**Comment by wwwlicious** [comment]
The target framework conditions now use a regex which ignores whitespace outwith the quote marks
