### ISSUE TITLE
VS2017 / .NET Core 2.0 - Build error in SQL project

### ISSUE THREAD

**Issue by ambujs** [cake-contrib/Cake.Incubator#61]
I'm trying to build a .NET Core 2.0 solution which has got a blank empty SQL Server project but getting this error:

```
MyDb.sqlproj(57,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.1.4\Microsoft\VisualStudio\v11.0\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.
targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

The solution builds correctly in VS2017 and also from command line if I call MSBuild directly like this:
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\msbuild.exe" MySolution.sln /t:build /fl /flp:logfile=MyProjectOutput.log;verbosity=diagnostic

Cake script looks like this:

```
Task("Build")
    .IsDependentOn("RestoreNuGetPackages")
    .IsDependentOn("SetVersion")
    .Does(() =>
{
   Information("Running DotNetCoreBuild");
	DotNetCoreBuild("../MySolution.sln", new DotNetCoreBuildSettings { 
		Configuration = configuration
   });
});
```

Any ideas why am I getting that error please?
Thanks

**Comment by wwwlicious** [comment]
@ambujs This doesn't appear to be using Cake.Incubator but rather Cake itself. You might want to raise this on the Cake repo - https://github.com/cake-build/cake
