### ISSUE TITLE
How do you call the ParseProject method from the ProjectParserExtensions

### ISSUE THREAD

**Issue by B3nCr** [cake-contrib/Cake.Incubator#62]
Hi

When I try to use ParseProject I get an error, it seems to be that another method with the alias already exists and I can't work out an easy way of using ParseProject from the ProjectParserExtensions.

I've managed to get it working but the way I've done it feels a bit dirty...

I've had to save a reference to the ICakeContext and then call the static ParseProject method specifying the full namespace...

```
ICakeContext context = null;
Setup(c => context = c);
Task("Compile").Does(() => 
{
     var projectProperties = Cake.Incubator.ProjectParserExtensions.ParseProject(context, projectFile, "Release");
    Information($"Project Properties: {projectProperties}");
    Information($"Project IsVS2017ProjectFormat: {projectProperties.IsVS2017ProjectFormat}");
});
```

**Comment by wwwlicious** [comment]
@B3nCr ah, this looks like a bug, I'll have a look at sorting this asap.

**Comment by wwwlicious** [comment]
@B3nCr version [1.7.2](https://www.nuget.org/packages/Cake.Incubator/1.7.2) will be available shortly on nuget,

I renamed the static method that was causing the conflict. You should hopefully be able to call `ParseProject(projectFile, "Release");` without the acrobatics!!! 

thanks for reporting it 👍

**Comment by B3nCr** [comment]
It's working now, does that mean Cake has pulled the latest version of the add-in down?

It's possible that I was doing it wrong.  I think I was passing the wrong parameters earlier 🙈

**Comment by gep13** [comment]
@B3nCr how are you adding the addin's to your Cake script?  via a packages.config file, or with a pre-processor directive?  If the latter, have you pinned to a specific version of the addin?  If not, Cake will pull the latest version on each run, that is part of why we recommend that you pin to a specific version of both Cake, and each addin, tool, and module that you use in your scripts.

**Comment by wwwlicious** [comment]
@gep13 wise words indeed 👍 You might want to bump receipe because of this bug btw...

**Comment by gep13** [comment]
@wwwlicious good idea!  I will get that done tomorrow.
