### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by nmbro** [cake-contrib/Cake.Incubator#70]
https://github.com/cake-contrib/Cake.Incubator/blob/8245e0a089a32c0d1c16e4f400096ec627d6a6e8/src/Cake.Incubator/FileExtensions.cs#L186

Gives following error

>  error CS0712: Cannot create an instance of the static class 'File'

If I don't include using System.Xml.Linq; in my build.cake I also get:

> error CS0246: The type or namespace name 'XDocument' could not be found (are you missing a using directive or an assembly reference?)

**Comment by wwwlicious** [comment]
@nmbro  Thank you for reporting this. I have included a reference to the package so hopefully you should not have to include this reference. The version published shortly 2.0.1 will include the fix.

**Comment by nmbro** [comment]
@wwwlicious 2.0.1 didn't solve either of my problems 😞 
Still getting the
> error CS0712: Cannot create an instance of the static class 'File

`Task("LoadConfiguration")
    .Does(() =>
{
    XDocument doc = new File("./code/Configuration.xml").LoadXml();
`

And that is following the documentation in https://github.com/cake-contrib/Cake.Incubator/blob/8245e0a089a32c0d1c16e4f400096ec627d6a6e8/src/Cake.Incubator/FileExtensions.cs#L186

What am I doing wrong?

**Comment by wwwlicious** [comment]
The error says File is static, therefore you can't use new.

```
XDocument doc = File("./proj.csproj").LoadXml(); 
```

I'll update the example

**Comment by nmbro** [comment]
Using the new example gives the following error:
> error CS1929: 'ConvertableFilePath' does not contain a definition for 'LoadXml' and the best extension method overload 'FileExtensions.LoadXml(IFile)' requires a receiver of type 'IFile

**Comment by wwwlicious** [comment]
@nmbro hmmm third time lucky I hope. You need GetFile instead of File!

```
XDocument doc = GetFile("./proj.csproj").LoadXml();
```

**Comment by nmbro** [comment]
GetFile gives this error
> error CS0103: The name 'GetFile' does not exist in the current context

**Comment by devlead** [comment]
Context.FileSystem.GetFile(...)?

**Comment by nmbro** [comment]
That did the trick:

`XDocument doc = Context.FileSystem.GetFile("./proj.csproj").LoadXml();`

But that is quiet a step away from new File() though 😄
