### ISSUE TITLE
Could not load Cake.Incubator.dll (missing netstandard, Version=2.0.0.0, Culture=neutral, ...)

### ISSUE THREAD

**Issue by warrenrumak** [cake-contrib/Cake.Incubator#71]
Full message:
`Could not load [elided]tools\Addins\Cake.Incubator.2.0.1\lib\netstandard2.0\Cake.Incubator.dll (missing netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)`

Started getting this error after 2.0.1 was released.  1.7.2 and 2.0.0 seem to be fine.

This is happening on a build server, but not on my workstation.  Could it be because the build server doesn't have the .NET Core SDK or something?

**Comment by wwwlicious** [comment]
@warrenrumak It sounds like that might be the case. I would either install the latest net core sdk onto your build server, or alternatively you can pin the version of incubator to 2.0.0 in your script.
```
#addin nuget:?package=Cake.Incubator&version=2.0.0
```

**Comment by zplan** [comment]
Same here. 
What exactly needs to be installed on a build server to build version 2.0.1 without "missing netstandard" error?

**Comment by rstam** [comment]
This is happening on my build server also, but not on my local machine.

Works fine with 2.0.0. The problem started with 2.0.1.

**Comment by alewmt** [comment]
`#addin "nuget:?package=Cake.Incubator&version=2.0.0"`
tried this and got another error

> Error: The assembly 'Cake.Incubator, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.22.0).
This assembly need to reference at least Cake.Core version 0.26.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt-out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)

**Comment by willnogueira** [comment]
Same issue here.

**Comment by wwwlicious** [comment]
What version of net core runtime do the servers have installed where it is failing?

**Comment by dga711** [comment]
I tried installing .net core sdk, didn't help. Installed .net core runtime, didn't help. Installed .NET 4.7.1, **WORKS**

**Comment by wwwlicious** [comment]
👍 Good to know @dga711. versioning is giving me a headache right now!

**Comment by dga711** [comment]
Yeah. It's a pain.
Can't think of a reason why installing 4.7.1 helps.

**Comment by zplan** [comment]
Any progress to this topic? Is there a new release coming?

**Comment by Structed** [comment]
I want to confirm that installing .NET FX 4.7.**1** resolves the issue. Thank you, @dga711!

**Comment by wwwlicious** [comment]
Should be reolved by #80
