### ISSUE TITLE
XUnit2Settings breaking change in cake 0.27.1 release

### ISSUE THREAD

**Issue by wwwlicious** [cake-contrib/Cake.Incubator#75]
There was a breaking change in ckae 0.27.1 release.

the `XUnit2Settings.Parallelism` property changed to be nullable.
When unspecified, this causes the cake alias in incubator
`DotNetCoreTest(this ICakeContext context,  DotNetCoreTestSettings settings, FilePath project, XUnit2Settings xunitSettings)` to throw an exception.

Add detection for null property value

**Comment by gep13** [comment]
@wwwlicious thank you for your quick turn around on this!

**Comment by wwwlicious** [comment]
@gep13 .. don't thank me yet, I added one to Receipe for you! 😀

**Comment by wwwlicious** [comment]
@gep13  - so it looks like dupfinder in receipe isnt happy on the build  because I changed the unit test project to multi-target (netstandard2.0 and net462)
...and it's picking up code copied to the obj folder which seems ... not ideal.

any suggestions on a quick way to resolve #lazyweb so I can get the release out?

**Comment by gep13** [comment]
@wwwlicious you can extend the number of files/folders that DupFinder looks in via the parameter in the setup.cake file.  Something like here:

https://github.com/cake-contrib/Cake.Gem/blob/develop/setup.cake#L18
