### ISSUE TITLE
Update build to use Cake 0.30.0

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Incubator#89]
Resolving of NuGet packages take AGES due to a problem with earlier NuGet client libraries.  This was resolved in Cake 0.30.0.

**Comment by gep13** [comment]
You can see this problem in action here:

https://ci.appveyor.com/project/cakecontrib/cake-incubator/builds/20970288

Where the build is taking over 10 minutes to even resolve the addins/tools.

**Comment by wwwlicious** [comment]
yeah I see that, cheers @gep13

**Comment by gep13** [comment]
@wwwlicious thanks for getting this merged!
