### ISSUE TITLE
Convert this repo to use Cake.Recipe

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Incubator#9]
@wwwlicious I am pretty much at the point where my not so secret project, Cake.Recipe, is ready to be rolled out.

Would you be interested in me adding it to this repository?

The benefits would be...

- a single place to control all the builds in the cake-contrib organisation
- access to notifications on twitter and gitter when new releases are available

Things that Cake.Recipe already does:

- Version with GitVersion
- Build
- Compile
- Run Unit Tests
- Submit results to coveralls.io
- NuGet Package everything
- Upload all artifacts to AppVeyor
- Runs DupFinder
- Runs InspectCode
- Handles publishing to both MyGet and NuGet (for interim releases)
- Runs GitLink, meaning that addin code is debuggable doing debug session in visual studio when debugging build.cake
- Documentation Website generation using Wyam

Probably other stuff that I have forgotten.

The main thing being, if we add something to Cake.Recipe, then all projects that are already using Cake.Recipe should be able to immediately take advantage of it.

Thoughts?  If you were interested, would you be happy to have me make the changes directly to repo, or would you prefer it as a PR?

**Comment by wwwlicious** [comment]
No issue with this at all @gep13.

Probably easier to update via PR and I can figure out after how to update readme and perhaps port documentation into method comments (or is there another way for website?)

**Comment by gep13** [comment]
@wwwlicious sweet!

what is currently used to generate the docs?

**Comment by gep13** [comment]
And where is the source for the docs?  Couldn't see it on initial pass through.

**Comment by wwwlicious** [comment]
The docs aren't generated, good ol' human powered! ;)

They are hosted on gitbooks rather than linked to a public repo so it'll likely just be an exercise of taking existing content and samples and cut/paste into code files
https://www.gitbook.com/book/wwwlicious/cake-incubator/details

**Comment by gep13** [comment]
Interesting.  We might be able to do something here then.  If we can move them into code, then we can use Wyam, similar to what is being done here:

https://cake-contrib.github.io/Cake.Coveralls/api/Cake.Coveralls/CoverallsAliases/

**Comment by gep13** [comment]
@wwwlicious quick question...

Cake.Recipe works best, when using GitFlow.  Any objections to be converting this repo to use a second main branch called develop, and then PR the changes to add Cake.Recipe into the develop branch?

**Comment by wwwlicious** [comment]
No we use gitflow internally, and some of our oss projects. develop branch created for you, crack on! :+1:

**Comment by gep13** [comment]
nice one, thank you!

**Comment by wwwlicious** [comment]
whoops, forgot to update develop to default, done now.
