### ISSUE TITLE
NullReferenceException on F# Project

### ISSUE THREAD

**Issue by kolesnick** [cake-contrib/Cake.Incubator#94]
Steps to Reproduce:
1. Download attached [Cake.Incubator.Issue.zip](https://github.com/cake-contrib/Cake.Incubator/files/2722095/Cake.Incubator.Issue.zip).
1. Unzip it.
1. Run `build.ps1`.
1. You should see following;

```
Error: One or more errors occurred.
        Object reference not set to an instance of an object.
```

P.S. Some of the older versions worked totally fine.

**Comment by wwwlicious** [comment]
Thanks for reporting and the sample. I'll take a look at what's going wrong.

In the meantime, you should be able to pin the version back to 3.0.0
