### ISSUE TITLE
ProjectParse cannot handle more complex conditions for TargetFrameworks

### ISSUE THREAD

**Issue by glennawatson** [cake-contrib/Cake.Incubator#95]
On some of our platforms we have fancy stuff to avoid Visual Studio 4 Mac compile issues

Such as 

```xml
    <TargetFrameworks>MonoAndroid81;Xamarin.iOS10;Xamarin.Mac20;Xamarin.TVOS10;Xamarin.WatchOS10;tizen40;netstandard2.0</TargetFrameworks>
    <TargetFrameworks Condition=" '$(OS)' == 'Windows_NT' ">$(TargetFrameworks);net461;uap10.0.16299</TargetFrameworks>
```

In your code you only ever evaluate the first value in the `TargetFramework` you come across.

**Comment by glennawatson** [comment]
I am probably going to convert over to using a class from Dave's project https://github.com/daveaglick/Buildalyzer

**Comment by glennawatson** [comment]
I have a workaround for my project where I reload the project, then 

```
    var document = XDocument.Load(projectPath.ToString());

    var targetFrameworkNodes = document.Descendants("TargetFrameworks")?
        .Select(x => (string)x.Value)
        .SelectMany(value => {
            return value.IsNullOrEmpty() ? new string[0] : value.Split(';', StringSplitOptions.RemoveEmptyEntries);
        })
        .Where(x => x != "$(TargetFrameworks)")
        .ToArray();
```

I guess maybe add a entry it only being in a `PropertyGroup` also would be suggested.

**Comment by wwwlicious** [comment]
the project xml doc is available in the parsed [response](https://www.cakebuild.net/api/Cake.Incubator/CustomProjectParserResult/DDE587FC) so you can do more bespoke parsing on conditions. 

What is available in the parsed response is mostly to aid making various decisions in builds rather than attempt to be a faithfull and full reproduction of 'what MSBuild does'

Overall, I don't think it is practical to implement a full-blown token parser, essentially attempting to replicate what MSBuild is already doing, but without the many external sources of data that MSBuild uses when building. 

You can run MSBuild with the /pp argument plus your intended build args and output the compiled project file to disk, this inlines things like includes too which this parser does not.

**Comment by glennawatson** [comment]
@wwwlicious Yep get that, and in this case I was using it for that exact case, I was replicating some logic in Cake.Recipe for our recipes and needed the output directories. Given it was only capturing the very first found `TargetFrameworks` only it was causing issues.  The simple fix would be capturing all TargetFrameworks instead.

**Comment by wwwlicious** [comment]
If you capture all the target framework elements, how do handle any conditions that are applicable to the elements?

**Comment by glennawatson** [comment]
Well the inverse is true though, given you just grab `TargetFrameworks` regardless of condition. Eg I've seen people do tricks like 

`<TargetFrameworks Condition="...is window condition...">net461</TargetFrameworks>`
`<TargetFrameworks>netcoreapp2.1</TargetFrameworks>`

So I suspect the current parsing would cause issues regardless in either case.

**Comment by glennawatson** [comment]
BTW feel free to reject this issue as well if you feel it's beyond what's required of the module. I have a work-around in this case where I do post-transformation after doing the parse project. I suspect you may want to look for the non-conditioned TargetFrameworks regardless.

**Comment by wwwlicious** [comment]
I don't disagree on the point you raise but I think either way is flawed without accounting for any conditions applicable and which as I said previously I think is beyond the scope of this parser to realistically implement correctly. So in this instance, given that you have a workaround, and the ability to access the project xml doc from the response for custom parsing on a case by case basis, 
I'd rather avoid changing existing behaviour which may break projects using it. 

I will opt to leave as is. Feel free to reopen if something changes.
