### ISSUE TITLE
'FilePath' does not contain a definition for 'IsProject'

### ISSUE THREAD

**Issue by danielmklein** [cake-contrib/Cake.Incubator#99]
After updating to version 4.0.0, we have started seeing the following error:

> error CS1061: 'FilePath' does not contain a definition for 'IsProject' and no accessible extension method 'IsProject' accepting a first argument of type 'FilePath' could be found (are you missing a using directive or an assembly reference?)

This occurs in the following block of code:
```csharp
var parsedSolution = ParseSolution(solutionPath);
var projects = parsedSolution.Projects
                .Where(p => p.Path.IsProject() && (ParseProject( p.Path, configuration.ToString() )
                                                    .IsType(ProjectType.AspNetMvc5) ))
                .Select(p => p);
```

Is this breaking change intentional? I did not see anything in the list of breaking changes for this release that suggested so, but please let me know if I missed it. And of course, let me know if there's more info I can provide that will help. In the meantime, we have pinned our usage of the add-in to 3.1.0.

**Comment by ZacUSNYR** [comment]
Same problem here but with other extension methods.

**Comment by wwwlicious** [comment]
The cake team raised an issue with alias name clashes and requested breaking the extension methods into different namespaces which is a breaking change and maj version change.. 

It should not really be a breaking change as far as cake scripts go though as all the namespaces in the addin should be imported by cake but this is obviously not happening in the cases above.

While it is investigated, if you can pin the version as you have done tp 3.1.0. 

Apologies for breaking your builds and thanks for reporting.
